# Generated by Django 2.2.7 on 2019-11-25 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
                ('location_city', models.CharField(max_length=50)),
                ('location_id', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='', max_length=50)),
                ('client_email', models.EmailField(default='', max_length=200)),
                ('branch_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checking_balance', models.FloatField(default=0, max_length=500)),
                ('client_connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.Client')),
            ],
        ),
    ]
